### ISSUE TITLE
"Com.Amap.Api" is missing?

### ISSUE THREAD

**Issue by sammy621** [code-jar/AMapBind#1]
The type or namespace name 'Maps' does not exist in the namespace 'Com.Amap.Api' ?There're errors in Project "AMap3DMap" ,when build

**Comment by code-jar** [comment]
The Demo project uses the <a src="https://github.com/code-jar/Others/blob/master/images/packref.png">local address</a> to refer to the DLL,
You have to compile a successful dependency set first.
In addition, you can use the nuget installation dependency

<a src="https://github.com/code-jar/Others/blob/master/images/3dmapasm.png">This is the assembly reflection information</a>

**Comment by code-jar** [comment]
The Demo project uses the local address to refer to the ,You have to compile a successful dependency set first https://github.com/code-jar/Others/blob/master/images/packref.png . 
In addition, you can use the nuget installation dependency https://www.nuget.org/packages?q=amap.xamarin

This is the assembly reflection information
https://github.com/code-jar/Others/blob/master/images/3dmapasm.png

**Comment by sammy621** [comment]
Thanks much! It's work!
